### ISSUE TITLE
[enhancement] Add support for ArcGIS for Desktop 10.2

### ISSUE THREAD

**Issue by ghost** [ChrisStayte/ArcMap-To-Google-Earth#1]
Hello.
Is there a chance to create a version that works in ArcGIS 10.2?

**Comment by chrisstayte** [comment]
Yes, I will work on this here and post it when it is done

**Comment by chrisstayte** [comment]
There is a 10.2 version

**Comment by ghost** [comment]
Would you be so kind as to upload the compiled version of the project site: [http://www.chrisstayte.com/Applications/ArcmapToGoogleEarth/](http://www.chrisstayte.com/Applications/ArcmapToGoogleEarth/)?

**Comment by chrisstayte** [comment]
I'll add it the website here when I get home.Thanks

**Comment by ghost** [comment]
Thank you. It's working :)
