### ISSUE TITLE
Disable Sync

### ISSUE THREAD

**Issue by muthagoose** [ChrisStayte/ArcMap-To-Google-Earth#2]
Wondering if it is possible to add a disable button that allows movement in Google Earth separately from Arcmap. As is currently, after clicking the sync button again Google Earth doesnt follow ArcMap, but you are unable to move inside of GE, it just keeps snapping back to its last known Arc position.

**Comment by chrisstayte** [comment]
This is because the network link is still existent. Let me see if I can come up with a solution and get back to you :)

**Comment by muthagoose** [comment]
NIce, thanks for the help. I have been looking for a solution like this for a while now.
As another possible improvement. Would it be possible to allow the movement inside of GE without having to turn of the tool? As it is now google earth will snap back to the synced location.
Basically i am looking to be able to zoom and pan in GE but use arcmap to jump me around to different locations.
Thanks 

    On Tuesday, April 4, 2017 1:36 PM, Chris Stayte <notifications@github.com> wrote:
 

 This is because the network link is still existent. Let me see if I can come up with a solution and get back to you :)—

**Comment by chrisstayte** [comment]
Check out the newest release :)

**Comment by muthagoose** [comment]
I am running 10.2.1 and adding the latest plugin version 1.2 to the ArcMap plugins folder, it doesnt show up, and when i point to it manually i get an error "No GUI components found in this Add-in. Add-In version does not match."

**Comment by chrisstayte** [comment]
Ahh, Yes I build the tool for 10.5. You can download the code and compile it for your version.

**Comment by muthagoose** [comment]
Hmm, not even sure how to go about doing that! Haha
