### ISSUE TITLE
Code Does not recognize ArcGIS on My Machine

### ISSUE THREAD

**Issue by shawno590** [ChrisStayte/ArcMap-To-Google-Earth#3]
I get this error when I try to install the download. 

![image](https://cloud.githubusercontent.com/assets/28570132/25859579/d565b6a8-3493-11e7-8e40-8496c6a958cb.png)

When I choose to install anyhow I cannot see the the tool in the Commands tab of the Customize window. I am currently running Arcmap 10.4 and also have pro installed on my machine.

**Comment by chrisstayte** [comment]
This is most likely the cause of you downloading the 10.5 version. I no longer support older versions on ArcMap, but you can download a past release of the tool. Here is a link to the version. 

https://github.com/ChrisStayte/ArcMap_To_Google_Earth/releases/tag/v10.4-1

**Comment by shawno590** [comment]
Thank you for the quick response. I was able to install the the 10.4 version . However, when I use the tool it opens ArcGIS Earth and the extent is random.

**Comment by chrisstayte** [comment]
This tool relies on the fact that Google Earth is the default program to open KMZ/KML file types. When installing ArcEarth this overrides the default which I assume was Google Earth. 

You can fix this by changing the default program associations. 

Here is a simple tutorial on how to do that from Microsoft. https://support.microsoft.com/en-us/help/18539/windows-7-change-default-programs

**Comment by shawno590** [comment]
Wow. It works great. I can now take advantage of googles imagery which is much better then ESRI's. Thanks!
