### ISSUE TITLE
Refresh ONLY on change

### ISSUE THREAD

**Issue by nickrupert7** [ChrisStayte/ArcMap-To-Google-Earth#5]
Thanks for your help on the last problem! A quick and easy solution that was! However, editing that one line in the source code didn't do exactly what I thought it would, and as the original developer, I was wondering if you had some insight in to how I might modify the code to make it do what I want...
Even when I set the refresh mode to `onChange`, and even put an "if" statement around the code inside `CreateTrackingKML` to only create a new KML if the values have actually changed (because I wasn't sure if that was the case already or not), Google Earth still refreshes/acts like it's getting a new request about 2 or 3 times a second. This means that at startup, and any time I travel a significant distance within my ArcMap project, the "fly to" animation is very slow, inching very slowly towards the destination before it finally gets there. When I disable the sync in Google Earth itself, it will fly to the destination, no problem, but of course that means whenever I want it to track me, I have to re-enable tracking, then disable it shortly after. In addition, once it's at the destination, it continues to bounce in and out ever so slightly.
I've played around with the KML settings and I just can't seem to get what I'm looking for... I'm trying to get it to only refresh Google Earth if I make a change in ArcMap without any kind of bouncing or stuttering.
Thanks again for your input! If you're able to help me get it working, I'll send you my changes to the source in case you want to implement this option in future releases.
Cheers!

P.S. I DID read the [KML reference](https://developers.google.com/kml/documentation/kmlreference) that google has available - I still couldn't figure it out

**Comment by chrisstayte** [comment]
Did you happen to read the instructions for installation and change the 'Fly-To' speed to a higher number?

**Comment by nickrupert7** [comment]
I did not, but I'm also not convinced that it's the fly-to speed that's a problem... When I turn off syncing, but the most recent sync request is still running, it will fly to the location almost instantly... It's the fact that new requests are constantly bombarding Google Earth, so it starts moving to its location, then half a second later it gets a new request, and although it's to the exact same place, it interrupts the previous movement with the "speed-up/slow-down" animation that it does at the beginning of new requests.
